[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"


[[mgr.prepend_keymap]]
on = ["c", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = "<A-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]
desc = "Copy to system clipboard"

[[mgr.prepend_keymap]]
on = ["c", "x"]
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "cd ~/.local"
desc = "Cd to ~/.local"

[[mgr.prepend_keymap]]
on = "<C-n>"                                          # Ctrl+D to trigger drag-and-drop
run = 'shell "dragon-drop -x -i -T \"$@\"" --confirm'
desc = "Drag selected files out of Yazi"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# If you also using Yazi on Windows:
[[mgr.prepend_keymap]]
on = "!"
for = "windows"
run = 'shell "wezterm.exe" --block'
desc = "Open PowerShell here"

# copy selected files to system clipboard while yanking
[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

# use the numbers directly to start a motion
[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["R", "b"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"
