background {
  monitor=
  blur_passes=0
  brightness=0.817200
  contrast=0.891600
  path=$FLAKE_PATH/modules/de-wm/hyprland/wallpapers/daniil-silantev-3pW91fGAKiE-unsplash.jpg
  vibrancy=0.169600
  vibrancy_darkness=0.000000
}

general {
  disable_loading_bar=false
  grace=0
  no_fade_in=false
}

image {
  monitor=
  size=700
  border_size=0
  halign=center
  path=$FLAKE_PATH/modules/de-wm/hyprland/wallpapers/foreground.png
  reload_cmd=
  reload_time=0
  rotate=0
  rounding=0
  valign=bottom
}

input-field {
  monitor=
  size=300, 60
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.200000
  fade_on_empty=false
  font_color=rgb(200, 200, 200)
  font_family=FiraMono Nerd Font
  halign=center
  hide_input=false
  inner_color=rgba(255, 255, 255, 0.1)
  outer_color=rgba(255, 255, 255, 0)
  outline_thickness=2
  placeholder_text=<i><span foreground="##ffffff99">🔒 Enter Pass</span></i>
  position=0, -250
  valign=center
}

label {
  monitor=
  color=rgba(216, 222, 233, .7)
  font_family=FiraMono Nerd Font
  font_size=160
  halign=center
  position=0, 370
  text=cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
  valign=center
}

label {
  monitor=
  color=rgba(216, 222, 233, .7)
  font_family=FiraMono Nerd Font
  font_size=28
  halign=center
  position=0, 490
  text=cmd[update:1000] echo -e "$(date +"%A, %d %B")"
  valign=center
}

label {
  monitor=
  color=rgba(216, 222, 233, 0.80)
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.200000
  font_family=FiraMono Nerd Font
  font_size=18
  halign=center
  outline_thickness=2
  position=0, -180
  text=    $USER
  valign=center
}
