exec-once = fcitx5
exec-once = bash -c "Telegram & sleep 5 && hyprctl dispatch closewindow 'class:^(org.telegram.desktop)$'"
exec-once = hyprpaper
exec-once = bash -c "qbittorrent & sleep 5 && hyprctl dispatch closewindow class:org.qbittorrent.qBittorrent"
exec-once = deluge
exec-once = clipse -listen
exec-once = swaync
# exec-once = spoofdpi --policy-auto --https-disorder
# exec-once = spoofdpi --dns-mode https --dns-https-url https://adguard.quannn.click/dns-query --policy-auto --https-disorder
