exec-once = fcitx5
exec-once = Telegram
exec-once = hyprpaper
exec-once = qbittorrent
exec-once = deluge
exec-once = clipse -listen
exec-once = swaync
# exec-once = spoofdpi --policy-auto --https-disorder
# exec-once = spoofdpi --dns-mode https --dns-https-url https://adguard.quannn.click/dns-query --policy-auto --https-disorder
exec-once = $FLAKE_PATH/modules/de-wm/hyprland/settings/scripts/close-app
