windowrule {
  name = windowrule-1
  float = on
  match:title = Picture-in-Picture
}

windowrule {
  name = windowrule-2
  move = (2043) (925)
  size = 476 268
  match:title = (Picture-in-Picture)
}


# Edge pip
windowrule {
  name = windowrule-3
  float = on
  match:title = ^(Picture in picture)$
}

windowrule {
  name = windowrule-4
  move = (2043) (925)
  size = 476 268
  match:title = (Picture in picture)
}


# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-5
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-6
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


windowrule {
  name = windowrule-7
  float = on
  match:class = (clipse) # ensure you have a floating window class set if you want this behavior
}

windowrule {
  name = windowrule-8
  size = 622 652
  match:class = (clipse) # set the size of the window as necessary
}

