] add speed 0.1
[ add speed -0.1
} add speed 0.5
{ add speed -0.5


# # ==========    GENERAL    ==========
Tab          script-binding uosc/toggle-ui
Shift+m      script-binding uosc/menu

h script-binding memo-history #! File > Open Recent
# # ========== uosc menu context default ============
g-s script-binding uosc/subtitles           #! Subtitles
g-a script-binding uosc/audio               #! Audio tracks
g-q script-binding uosc/stream-quality      #! Stream quality
g-p script-binding uosc/items               #! Playlist
g-c script-binding uosc/chapters            #! Chapters

> script-binding uosc/next                #! Navigation > Next
< script-binding uosc/prev                #! Navigation > Prev
o script-binding uosc/open-file           #! Navigation > Open file

# set video-aspect-override "-1"     #! Utils > Aspect ratio > Default
# set video-aspect-override "16:9"   #! Utils > Aspect ratio > 16:9
# set video-aspect-override "4:3"    #! Utils > Aspect ratio > 4:3
# set video-aspect-override "2.35:1" #! Utils > Aspect ratio > 2.35:1

g-D script-binding uosc/audio-device    #! Utils > Audio devices
s async screenshot                   #! Utils > Screenshot
ctrl+k script-binding uosc/keybinds        #! Utils > Key bindings
Shift+s     async screenshot video                    	#! Utils > Screenshot (Without Subtitles)
Ctrl+s      async screenshot window                   	#! Utils > Screenshot (Window)
g-d script-binding uosc/show-in-directory #! Utils > Show in directory
g-C script-binding uosc/open-config-directory #! Utils > Open config folder
Q quit                                    #! Quit

